name: Pull Request
on:
  pull_request:

jobs:
  pullrequest:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.4.0

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      # Run ktlint
      - name: Run KtLint
        run: ./gradlew lintKotlin

      - name: Collect KtLint Result
        if: ${{ failure() }}
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew formatKotlin
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
          cat ${{ github.workspace }}/build/reports/ktlint/main-lint.xml | ./bin/reviewdog -name="ktlint" -f=checkstyle -diff="git diff" -reporter=github-pr-review -level="error" -fail-on-error="false"